TRACKER_APP_NAME = "tracker"
HOME_PATH_NAME = "home"
HISTORY_PATH_NAME = "history"
MEASUREMENT_DETAIL_PATH_NAME = "measurement-detail"
MEASUREMENT_CREATE_PATH_NAME = "measurement-create"
MEASUREMENT_UPDATE_PATH_NAME = "measurement-update"
MEASUREMENT_DELETE_PATH_NAME = "measurement-delete"
USER_MEASUREMENT_TYPES_PATH_NAME = "user-measurement-types"
